[View in Colaboratory](https://colab.research.google.com/github/HUSTneeb/GoogleColabCode/blob/master/TensorFLowLearning6.ipynb)

In [0]:
import tensorflow as tf
tf.enable_eager_execution()

In [2]:
print(tf.add(1,2))
print(tf.add([1,2],[3,4]))

tf.Tensor(3, shape=(), dtype=int32)
tf.Tensor([4 6], shape=(2,), dtype=int32)


In [3]:
print(tf.square(5))

tf.Tensor(25, shape=(), dtype=int32)


In [4]:
print(tf.reduce_sum([1,2,3]))

tf.Tensor(6, shape=(), dtype=int32)


In [5]:
print(tf.encode_base64("hello world"))

tf.Tensor(b'aGVsbG8gd29ybGQ', shape=(), dtype=string)


In [8]:
print(tf.square(2)+tf.square(3))

tf.Tensor(13, shape=(), dtype=int32)


In [9]:
x=tf.matmul([[1]],[[2,3]])
print(x.shape)
print(x.dtype)

(1, 2)
<dtype: 'int32'>


In [10]:
import numpy as np

ndarray=np.ones([3,3])
print("TensorFlow op convert numpy arrays to Tensors automatically")
tensor=tf.multiply(ndarray,42)
print(tensor)

print("And NumPy operations convert Tensors to numpy arrays automatically")
print(np.add(tensor,1))

print("The .numpy() method explictly converts a Tensor to a numpy array")
print(tensor.numpy())

TensorFlow op convert numpy arrays to Tensors automatically
tf.Tensor(
[[42. 42. 42.]
 [42. 42. 42.]
 [42. 42. 42.]], shape=(3, 3), dtype=float64)
And NumPy operations convert Tensors to numpy arrays automatically
[[43. 43. 43.]
 [43. 43. 43.]
 [43. 43. 43.]]
The .numpy() method explictly converts a Tensor to a numpy array
[[42. 42. 42.]
 [42. 42. 42.]
 [42. 42. 42.]]


In [11]:
x=tf.random_uniform([3,3])
print("Is there a GPU available: ")
print(tf.test.is_gpu_available())

print("Is the Tensor on GPU#0: ")
print(x.device.endswith('GPU:0'))

Is there a GPU available: 
False
Is the Tensor on GPU#0: 
False


In [13]:
def time_matmul(x):
  %timeit tf.matmul(x,x)
  
print("On CPU:")
with tf.device("CPU:0"):
  x=tf.random_uniform([1000,1000])
  assert x.device.endswith("CPU:0")
  time_matmul(x)
  
if tf.test.is_gpu_available():
  with tf.device("GPU:0"):
    x=tf.random_uniform([1000,1000])
    assert x.device.endswith("GPU:0")
    time_matmul(x)
    
    

On CPU:
10 loops, best of 3: 21.7 ms per loop


In [0]:
ds_tensors=tf.data.Dataset.from_tensor_slices([1,2,3,4,5,6])

import tempfile
_,filename=tempfile.mkstemp()

with open(filename,'w') as f:
  f.write("""Line 1
  Line 2
  Line3
  """)
  
ds_file=tf.data.TextLineDataset(filename)

In [16]:
print('Elements of ds_tensors:')
for x in ds_tensors:
  print(x)
  
print('\nElements in ds_file:')
for x in ds_file:
  print(x)
  

Elements of ds_tensors:
tf.Tensor(1, shape=(), dtype=int32)
tf.Tensor(2, shape=(), dtype=int32)
tf.Tensor(3, shape=(), dtype=int32)
tf.Tensor(4, shape=(), dtype=int32)
tf.Tensor(5, shape=(), dtype=int32)
tf.Tensor(6, shape=(), dtype=int32)

Elements in ds_file:
tf.Tensor(b'Line 1', shape=(), dtype=string)
tf.Tensor(b'  Line 2', shape=(), dtype=string)
tf.Tensor(b'  Line3', shape=(), dtype=string)
tf.Tensor(b'  ', shape=(), dtype=string)
