[View in Colaboratory](https://colab.research.google.com/github/HUSTneeb/GoogleColabCode/blob/master/TensorFlowLearning9.ipynb)

In [0]:
import tensorflow as tf
tfe=tf.contrib.eager
tf.enable_eager_execution()

In [0]:
layer=tf.keras.layers.Dense(100)
layer=tf.keras.layers.Dense(10,input_shape=(None,5))

In [9]:
class MyDenseLayer(tf.keras.layers.Layer):
  def __init__(self,num_outputs):
    super(MyDenseLayer,self).__init__()
    self.num_outputs=num_outputs
    
  def build(self,input_shape):
    self.kernel=self.add_variable("kernel",
                                shape=[input_shape[-1].value,self.num_outputs])
    
  def call(self,input):
    return tf.matmul(input,self.kernel)
  
layer=MyDenseLayer(10)
print(layer(tf.zeros([10,5])))
print('\n')
print(layer.variables)

tf.Tensor(
[[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]], shape=(10, 10), dtype=float32)


[<tf.Variable 'my_dense_layer_4/kernel:0' shape=(5, 10) dtype=float32, numpy=
array([[-0.20175844, -0.24054247,  0.26149762,  0.12034768,  0.37843865,
         0.57949823, -0.30296496,  0.53803605,  0.37135237, -0.5350679 ],
       [-0.49130076,  0.54016906,  0.5828422 , -0.13097697,  0.00532722,
         0.32073742,  0.30109167, -0.00188756,  0.33700758,  0.21858138],
       [-0.4162367 , -0.5903938 ,  0.53521806,  0.51655763,  0.06300515,
        -0.49674952, -0.4069342 , -0.28182837, -0.57391435, -0.20518136],
       [-0.13089114, -0.5641146 ,  0.51912385,  0.4793226 ,  0.12487543,
         0.54704195, -0.28550446

In [13]:
class ResnetIdentityBlock(tf.keras.Model):
  def __init__(self,kernel_size,filters):
    super(ResnetIdentityBlock,self).__init__(name='')
    filters1,filters2,filters3=filters
    
    self.conv2a=tf.keras.layers.Conv2D(filters1,(1,1))
    self.bn2a=tf.keras.layers.BatchNormalization()
    
    self.conv2b=tf.keras.layers.Conv2D(filters2,kernel_size,padding='same')
    self.bn2b=tf.keras.layers.BatchNormalization()
    
    self.conv2c=tf.keras.layers.Conv2D(filters3,(1,1))
    self.bn2c=tf.keras.layers.BatchNormalization()
    
  def call(self,input_tensor,training=False):
    x=self.conv2a(input_tensor)
    x=self.bn2a(x,training=training)
    x=tf.nn.relu(x)
    
    x=self.conv2b(x)
    x=self.bn2b(x,training=training)
    x=tf.nn.relu(x)
    
    x=self.conv2c(x)
    x=self.bn2c(x,training=training)
    
    x+=input_tensor
    return tf.nn.relu(x)
  
block=ResnetIdentityBlock(1,[1,2,3])
print(block(tf.zeros([1,2,3,3])))
print([x.name for x in block.variables])
  
    

tf.Tensor(
[[[[0. 0. 0.]
   [0. 0. 0.]
   [0. 0. 0.]]

  [[0. 0. 0.]
   [0. 0. 0.]
   [0. 0. 0.]]]], shape=(1, 2, 3, 3), dtype=float32)
['resnet_identity_block_3/conv2d_9/kernel:0', 'resnet_identity_block_3/conv2d_9/bias:0', 'resnet_identity_block_3/batch_normalization_9/gamma:0', 'resnet_identity_block_3/batch_normalization_9/beta:0', 'resnet_identity_block_3/conv2d_10/kernel:0', 'resnet_identity_block_3/conv2d_10/bias:0', 'resnet_identity_block_3/batch_normalization_10/gamma:0', 'resnet_identity_block_3/batch_normalization_10/beta:0', 'resnet_identity_block_3/conv2d_11/kernel:0', 'resnet_identity_block_3/conv2d_11/bias:0', 'resnet_identity_block_3/batch_normalization_11/gamma:0', 'resnet_identity_block_3/batch_normalization_11/beta:0', 'resnet_identity_block_3/batch_normalization_9/moving_mean:0', 'resnet_identity_block_3/batch_normalization_9/moving_variance:0', 'resnet_identity_block_3/batch_normalization_10/moving_mean:0', 'resnet_identity_block_3/batch_normalization_10/moving_var

In [14]:
myseq=tf.keras.Sequential([tf.keras.layers.Conv2D(1,(1,1)),
                          tf.keras.layers.BatchNormalization(),
                          tf.keras.layers.Conv2D(2,1,padding='same'),
                          tf.keras.layers.BatchNormalization(),
                          tf.keras.layers.Conv2D(3,(1,1)),
                          tf.keras.layers.BatchNormalization()])
myseq(tf.zeros([1,2,3,3]))

<tf.Tensor: id=751, shape=(1, 2, 3, 3), dtype=float32, numpy=
array([[[[0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.]]]], dtype=float32)>